version: '3.5'

services:
  angular-service:
    container_name: angularcontainer
    build: ./frontend
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - '4200:4200'
    expose:
      - '4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'mindplus'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

